apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: dns-record
spec:
  endpoints:
  - dnsName: app.itea.devopsology.org
    recordType: CNAME
    targets:
    - traefik-ext.itea.devopsology.org
