apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route
  annotations:
    kubernetes.io/ingress.class: "traefik-ext-dev"
spec:
  routes:
  - kind: Rule
    match: Host(`app.itea.devopsology.org`)
