apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: service/nginx
  newName: 438378284830.dkr.ecr.eu-west-1.amazonaws.com/service/nginx
  newTag: "1.0"
namespace: default
resources:
- ../../base
patchesStrategicMerge:
- conf-ingressroute.yaml
- conf-dns-endpoint.yaml
